on:
  push:
jobs:
  push-monitors:
    defaults:
      run:
        working-directory: cloud-demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npx @elastic/synthetics push --auth ${{ env.CLOUD_DEMO_API_KEY }}