on:
  push:
    branches: [main, master]
      #  pull_request:
      #    branches: [main, master]
env:
  SYNTHETICS_API_KEY: ${{ secrets.SYNTHETICS_API_KEY }}
permissions:
  contents: read

jobs:
  push-monitors:
    defaults:
      run:
        working-directory: cloud-demo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npx @elastic/synthetics push
